### ISSUE TITLE
[Bug] Hint tab in dev tools is blank when "Block third-party cookies" is enabled

### ISSUE THREAD

**Issue by keeganwitt** [webhintio/hint#3590] opened 2020-03-05 04:08 UTC
# 🐛 Bug report

## Description

Steps:

1. Got to edge://settings
1. Site permissions
1. Enable block third-party cookies

![image](https://user-images.githubusercontent.com/606594/76256095-9492ce00-620c-11ea-88b7-15eaf9365172.png)

Once enabled, go to any website, open the devtools and switch to the Hint tab. It will be blank.

------------------------------------------------

Original report:

Using the extension in Vivaldi shows a blank hints tab in developer tools.

## Environment

* __webhint version:__ 2.0.3
* __Browser version:__ Vivaldi 2.12.1838.3 (Snapshot)

## Debug output

No errors in console.

**Comment by liprec** [comment] 2020-03-06 17:18
I had a similar issue with the new Edge (Chromium).
Apparently the extension needs to be able to set cookies/access site data: I solved it by adding `chrome-extension://mlgfbihcfnkaenjpdcngdnhcpkdmcdee` to the allowed sites for cookies and site data.

**Comment by molant** [comment] 2020-03-06 18:03
I'd assume that the permissions prompt would take care of that so it might be an issue upstream 🤔

@liprec what version and channel of Edge were you running?
I'll try to repro on my side.

**Comment by liprec** [comment] 2020-03-06 18:30
Edge Dev channel (Version 82.0.439.1 (Official build) dev (64-bit)) with the webhint 2.0.3 extension

**Comment by molant** [comment] 2020-03-06 18:49
I can't seem

**Comment by molant** [comment] 2020-03-06 18:51
I can't seem to reproduce this 😢
I have installed the latest beta and dev channels but the extension always shows up.

Few follow up questions to try to narrow this:

* How do you run the dev tools? Docked? Floating?
* What theme are your running? Dark? Light?
* Did you installed the extension from the Edge store or the Chrome store?
* What URL were you testing?

**Comment by liprec** [comment] 2020-03-06 18:52
Don't know if it helps, but I have by default third party cookies blocked and tracking set to strict

**Comment by molant** [comment] 2020-03-06 19:02
> Don't know if it helps, but I have by default third party cookies blocked and tracking set to strict

So you have this option set, correct?

![image](https://user-images.githubusercontent.com/606594/76113920-df58df80-5f99-11ea-94fb-6906a6adf7b8.png)

**Comment by liprec** [comment] 2020-03-06 19:04
Yes.

**Comment by liprec** [comment] 2020-03-06 19:07
For more info via the devtools of the devtools I can see the extension error:
![image](https://user-images.githubusercontent.com/12474072/76114260-fc1b0480-5fe5-11ea-87fe-eae71ba1cdbb.png)

**Comment by molant** [comment] 2020-03-06 19:10
Does that error show up in another page (like https://webhint.io)?
I know GitHub is using CSP so this particular error could be related (although I think that @antross found a workaround)

**Comment by liprec** [comment] 2020-03-06 19:12
Yes, just test it and the same error appears on webhint.io.

**Comment by molant** [comment] 2020-03-06 19:33
So it looks like the localstorage issue is fixed already in the code but we haven't shipped it yet 🤦‍♂️
Need to still figure out the blank screen though (haven't tested with strict yet)

**Comment by molant** [comment] 2020-03-07 00:04
I cannot reproduce this 😭
I don't even get the `localStorage` issue when running on webhint.io:

![image](https://user-images.githubusercontent.com/606594/76131641-252a9d80-5fc4-11ea-9674-d4949b6c5997.png)

Do you have the telemetry enabled?

**Comment by keeganwitt** [comment] 2020-03-07 02:49
I think my issue might have been similar.  I had enabled the new tracking protection that landed in Vivaldi Snapshot channel (https://vivaldi.com/blog/snapshots/desktop/tracking-blocker-vivaldi-browser-snapshot-1838-3/).  I have it disabled now, and the tab is showing up again.

**Comment by liprec** [comment] 2020-03-07 17:48
@molant I don't the telemetry of the extension running. The settings are (probably) the default as I cannot change anything due to the blank screen.

**Comment by molant** [comment] 2020-03-08 00:36
I'll try installing the extension with the strict setting on by default as soon as I can.
I tried changing it after and didn't change anything.
Don't think telemetry on/off should change anything but who knows...

**Comment by molant** [comment] 2020-03-08 03:48
Even if I install with strict enabled previously I cannot reproduce the issue.

@liprec If you go to [edge://extensions/?id=gccemnpihkbgkdmoogenkbkckppadcag](edge://extensions/?id=gccemnpihkbgkdmoogenkbkckppadcag) what do you see?
This is what mine looks like:

![image](https://user-images.githubusercontent.com/606594/76156246-8037bf80-60ac-11ea-8dc9-f554d48979e5.png)

@antross I'm running out of ideas on how to get a repro of this 😓

**Comment by liprec** [comment] 2020-03-08 12:40
Here is my screenshot: 
![image](https://user-images.githubusercontent.com/12474072/76162929-4ca77480-6142-11ea-925a-5ffa3ac69121.png)

**Comment by Malvoz** [comment] 2020-03-08 13:27
> So it looks like the localstorage issue is fixed already in the code but we haven't shipped it yet 🤦‍♂️
> Need to still figure out the blank screen though

This issue seems to be the same thing I reported in https://github.com/webhintio/hint/issues/3494 - while I didn't mention it - I also got a blank Hint tab (in Chrome dev tools). Until the update is shipped, I have to allow 3P cookies to use the extension.

**Comment by keeganwitt** [comment] 2020-03-08 18:26
Actually, I misspoke earlier when I thought it was caused by blocking trackers, it was caused by blocking 3P cookies.  This isn't specific to Vivaldi, or any other Chromium browser, I can reproduce it in Chrome by turning off 3P cookies there as well.

**Comment by molant** [comment] 2020-03-09 20:50
Thanks a lot @keeganwitt, I can now repro this in the latest stable version of Edge!

Steps:

1. Got to edge://settings
1. Site permissions
1. Enable block third-party cookies

![image](https://user-images.githubusercontent.com/606594/76256095-9492ce00-620c-11ea-88b7-15eaf9365172.png)

Once enabled, go to any website, open the devtools and switch to the Hint tab. It will be blank.

I'll update the issue title and steps in the first comment.

@antross, this seems to be platform related and coming directly from Chromium. Should I add the tag "msft-consider" so someone in Edge can take a better look?

**Comment by antross** [comment] 2020-03-09 21:01
@molant I don't think we need to track this as a separate issue. The workaround from #3494 should "fix" this in the next webhint release (localStorage still won't work, but the extension will gracefully handle it). 

The underlying unexpected platform behavior has a tracking Chromium bug which would be the right place to +1: https://bugs.chromium.org/p/chromium/issues/detail?id=971848

**Comment by molant** [comment] 2020-03-09 21:12
Then hurry up and do a new release 😛

**Comment by antross** [comment] 2020-03-23 23:00
This should now be fixed with the recently released version `2.1.0` of the browser extension. I confirmed webhint works in that version even when 3rd party cookies have been disabled.

**Closed by antross** 2020-03-23 23:00 UTC
Labels: area:browser-extension, msft-consider, priority:high, type:bug
