### ISSUE TITLE
[Bug] Learn more link does not work in Firefox

### ISSUE THREAD

**Issue by sysofwan** [webhintio/hint#3136] opened 2019-10-18 17:11 UTC
# 🐛 Bug report
Clicking on learn more link does not open the url

## Description
After scanning for issues, clicking learn more does not do anything

## Environment

* __webhint version:__ 1.0.3
* __Browser version:__ Firefox 69.0.3
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment] 2019-10-18 17:17
Thanks @sysofwan! I'm guessing this is probably a duplicate of #3015. Can you confirm?

**Comment by sysofwan** [comment] 2019-10-18 18:15
Yes, this a a dupe

**Comment by antross** [comment] 2019-10-18 18:20
Thanks for confirming!

**Closed by antross** 2019-10-18 18:20 UTC
Labels: area:browser-extension, type:bug
