### ISSUE TITLE
Migrate to use ES Modules

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2196] opened 2019-04-09 21:56 UTC
# 🚀 Feature request

## Description

We still have a few `require`s in the code and some dependencies that prevent us from doing treeshaking. We should look into all of these and enable it.

This will help reduce the footprint as well (#1824)

**Comment by antross** [comment] 2019-06-10 17:16
Duplicate of #2096

**Closed by antross** 2019-06-10 17:15 UTC
Labels: area:api, enhancement
