### ISSUE TITLE
[Bug] Expand/collapse icons don't appera in hint results next to hit categories in FF DevTools

### ISSUE THREAD

**Issue by brendyna** [webhintio/hint#2591] opened 2019-06-11 22:45 UTC
# 🐛 Bug report

## Description

I ran the report on microsoftedgeinsider.com and when the results displayed there were no arrow icons next to each section of hints (screenshot attached).

## Environment

* __webhint version:__ 0.0.3
* __Browser version:__ 67.0.2 (64-bit)
* __Operating system:__ Windows 10
* __URL for which webhint failed:__ https://www.microsoftedgeinsider.com/en-us/

## Screenshot
![image](https://user-images.githubusercontent.com/4712801/59311860-dda6f900-8c5f-11e9-9e08-8cc35d2ee624.png)

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by antross** [comment] 2019-06-11 22:59
Thanks for reporting! This is a dupe of https://github.com/webhintio/hint/issues/2586 for which a fix just merged into `master` today. I'll try to release an update to the extension itself tomorrow.

**Closed by antross** 2019-06-11 22:59 UTC
Labels: type:bug
