### ISSUE TITLE
[Bug] Layout in telemetry prompt is incorrect in Chrome Canary/Dev

### ISSUE THREAD

**Issue by antross** [webhintio/hint#3132] opened 2019-10-18 14:44 UTC
Note the position of the "X":

Incorrect (Chromium Canary and Dev builds):
![image](https://user-images.githubusercontent.com/785009/67103908-a5727280-f18b-11e9-984f-d19642a7bb4f.png)

Correct (Firefox, Chromium Beta and Stable builds):
![image](https://user-images.githubusercontent.com/785009/67104001-ccc93f80-f18b-11e9-8bb4-5bdbb7a51fb4.png)

Filed a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1015162, but was resolved as a By Design change in CSS Grid to align with the spec. We'll need to update to adapt to the change.

**Comment by antross** [comment] 2019-10-18 16:31
I think the workaround should be fairly simple. Currently the JSX for the controls in https://github.com/webhintio/hint/blob/master/packages/extension-browser/src/devtools/views/controls/notification.tsx looks like this:
```jsx
<div className={`${styles.root}`} hidden={!show || dismissed}>
    <div>
        {children}
    </div>
    <Button className={styles.close} title={closeMessage} onClick={onDismissNotification} />
    {actions && <div className={styles.actions}>{actions}</div>}
</div>
```

And the styles organize it into a grid with two rows and two columns, with the actions spanning the second row and organized into their own sub-grid.

One possible fix would be to adjust the top-level grid to be two rows with just one column. Then the close button could be merged into the first cell with the content div by wrapping them in a shared container. Finally, the content div and close button could be organized within that cell as a sub-grid with one row and two columns.

**Comment by sarvaje** [comment] 2019-11-21 16:47
I can't reproduce this.

This is how it looks like in my PC:

![image](https://user-images.githubusercontent.com/1581288/69358332-88720900-0c3b-11ea-915e-3d4887ea1c47.png)

**Comment by molant** [comment] 2019-11-21 17:15
In latest edge canary?
@antross did a bit of research and it looked like a change in the spec


________________________________

**Comment by sarvaje** [comment] 2019-11-21 17:23
Edge canary is my default browser hahaha. I have try also chrome canary and I can't reproduce it :s

**Comment by molant** [comment] 2019-11-21 17:37
Maybe they changed their minds. Going to close this then.

**Closed by molant** 2019-11-21 17:37 UTC
Labels: Hacktoberfest, area:browser-extension, good first issue, type:bug
