### ISSUE TITLE
[docs] Issue with 'Axe: Forms'

### ISSUE THREAD

**Issue by mosro** [webhintio/hint#4545] opened 2021-05-10 07:05 UTC
https://webhint.io/docs/user-guide/hints/hint-axe/forms/index.html

**Comment by masi** [comment] 2021-05-17 18:46
What exactly is the issue?

**Comment by hxlnt** [comment] 2021-05-27 21:46
Will close this for now, as we cannot repro without information about what the problem is. If you're still experiencing an issue with these docs, please include a description of the issue so that we can address it. Thanks!

**Closed by hxlnt** 2021-05-27 21:46 UTC
