### ISSUE TITLE
[Bug] Focus style bug in browser extension

### ISSUE THREAD

**Issue by ststimac** [webhintio/hint#3048] opened 2019-09-30 08:36 UTC
# 🐛 Bug report

## Description

There's a contrast issue with the inputs when you start up the extension. The text is black until you select the input and give it focus, in which case it then turns white. 

![focus-bug](https://user-images.githubusercontent.com/18073131/65862029-a888f880-e36d-11e9-8158-efe6fe6a9559.PNG)

## Environment

* __webhint version:__  1.03
* __Browser version:__  Edge Canary Version 79.0.286.0
* __URL for which webhint failed:__  n/a

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom: 

Ignored resources:
* [x] None
* [ ] Different origin
* [ ] Custom: 

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
<!-- ✍️ Paste the error details here -->


```

</details>

**Comment by molant** [comment] 2019-09-30 08:46
Yeah, that's a change (bug?) in chromium upstream. I believe Amanda has filed and issue because she had some problems with it too in other parts of the devtools.
@antross might have a bit more info.


________________________________

**Comment by antross** [comment] 2019-09-30 16:59
Yes, this is a Chromium bug. I couldn't find the original issue I was looking for, but I found two other bugs related to this that both tie back to the same regressing change:
* https://bugs.chromium.org/p/chromium/issues/detail?id=1009285
* https://bugs.chromium.org/p/chromium/issues/detail?id=1009424

The first one is currently marked as stable blocking so I'd expect to see this fixed there.

**Comment by sarvaje** [comment] 2020-01-17 21:32
I can't reproduce it in the latest stable version of chrome neither edge

**Comment by molant** [comment] 2020-01-17 21:46
Let's close this then!

**Closed by molant** 2020-01-17 21:46 UTC
Labels: area:browser-extension, type:bug
