### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by JanGray** [webhintio/hint#4685] opened 2021-07-27 01:18 UTC
# 🐛 Bug report

## Environment

* __webhint version:__ 2.3.2 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [ ] None
* * [x] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Scan timed out.



```

</details>

**Comment by hxlnt** [comment] 2021-08-13 15:21
Closing as this appears to be a duplicate of #4686

**Closed by hxlnt** 2021-08-13 15:21 UTC
Labels: type:bug, area:browser-extension
