### ISSUE TITLE
[Bug] Make hint-compat-api tests more reliable

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2197] opened 2019-04-09 22:26 UTC
Currently the tests for `hint-compat-api` fail frequently in CI and on some users' machines. This hint contains a large number of tests compared to other hints. This is suspected to be one of the factors contributing to failures as it results in a large number of server and browser instances being spawned concurrently while running the tests.

Potential remedies:
* [x] Reuse the same browser instance across tests (#2203)
* [ ] Reuse the same server instance across tests (original issue #1780)
* [ ] Split the tests into multiple files

**Comment by molant** [comment] 2019-04-10 03:34
So the `compat-api` tests are failing more often in macOS now. The reason is macOS behavior of not fully closing an app when you close all its windows and then we are having race conditions when sending the signal to terminate it.

If we only close the tabs then these tests run OK. The problem is that there's a timeout of 2 minutes between getting the ava results and seeing the nyc codecoverage. We have 65+ hints so that's totally unnaceptable. I believe it's because the connection via the debugging protocol might still be active and is waiting to time out.

Things I'm going to try:

* [ ] Close the `client` but don't send any kill signal (`SIGINT` or `SIGKILL`) when running the tests (maybe only on mac?)
* [ ] See if I can find the applications that are running but don't have any window (and then query the app during a few seconds and if nothing has changed stop it)
* [ ] Find a dark spell to make this thing work magically

Any other ideas are welcome!

**Comment by molant** [comment] 2019-04-12 03:27
Even though CI is passing now without too much trouble (only 2 tests when in CI) @shivangg is still having problems with `hint-compat-api` tests on his machine. The other option is to split the tests into multiple files. We have 120+ so this is going to be more monkey work than anything else :(

I'll add the option to the top.

@webhintio/contributors thoughts about this?

**Comment by molant** [comment] 2019-04-12 03:36
@antross, the proposal of running the test server in the same thread was already tracked in #1780. I might try to do that tomorrow if I have time but that will only affect the CI scenario that we are already passsing. Maybe I can use an environment variable or something on top of `is-ci` to decide what to do?

**Closed** 2019-04-12 17:21 UTC
Labels: area:hint, type:bug
