### ISSUE TITLE
[Bug] Bug description

### ISSUE THREAD

**Issue by akraman0959** [webhintio/hint#4033] opened 2020-09-24 06:44 UTC
# 🐛 Bug report

## Environment

* __webhint version:__ 2.1.4 
* __Browser version:__ Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0 
* __URL for which webhint failed:__ 

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

Categories:
* [x] Accessibility
* [x] Compatibility
* [x] Performance
* [x] Pitfalls
* [x] PWA
* [x] Security

Your target browsers:
* [x] Recommended settings
* [ ] Custom:  

Ignored resources:
* * [x] None
* * [ ] Different origin
* * [ ] Custom:  

</details>

## Debug output

Please include the content of the `Error details` section if an error message was displayed.

<details>
<summary>webhint’s Error details</summary>

```text
Failed to inject content script after retrying.



```

</details>

**Comment by molant** [comment] 2020-09-24 15:47
Hi @akraman0959,

can you please provide the URL where this happens? Otherwise we cannot take a look at it.

**Comment by hxlnt** [comment] 2020-10-28 16:13
@akraman0959 Friendly ping to provide us more information on this bug. If we don't hear back, we'll assume the issue is now resolved and will close the issue. Thanks!

**Closed** 2020-12-04 17:24 UTC
Labels: area:browser-extension, type:bug
