### ISSUE TITLE
[Bug] jsdom connector doesn't support `fetch`

### ISSUE THREAD

**Issue by iondrimba** [webhintio/hint#1586] opened 2018-12-16 21:01 UTC
# 🐛 Bug report

## Description

Still having the same problem as this closed issue https://github.com/webhintio/hint/issues/1299

Scan result: https://webhint.io/scanner/0c8a80c5-43e2-46ce-9bcc-06eb3d31dabe

## Environment

* __`hint` version:__ 
* __`Node.js` version:__ 
* __`OS`:__ 
* __URL for which webhint failed:__  https://webhint.io/scanner/0c8a80c5-43e2-46ce-9bcc-06eb3d31dabe

## `webhint` configuration

<details>
<summary>webhint’s configuration</summary>

```js
<!-- Paste the content of your `.hintrc` here -->

```

</details>

## Debug output

Please include the raw output generated by `webhint`, or if possible,
the raw output from running `webhint` in debug mode: `hint --debug <URL>`.

<details>
<summary>webhint’s raw output</summary>

```text
<!-- ✍️ Paste the raw output here -->


```

</details>

**Comment by molant** [comment] 2018-12-16 21:40
@sarvaje can you please take a look at this? We should just display a general error message instead of one in each hint.


________________________________

**Comment by sarvaje** [comment] 2018-12-17 18:04
I have taken a look, and the problem is that `fetch` is not supported by jsdom. https://github.com/jsdom/jsdom/issues/1724

IIRC, I tried to add the `whatwg-fetch` polyfill to the `beforeParse`, but it was throwing another errors.

**Comment by molant** [comment] 2018-12-17 18:05
But we should print only one general error instead of in every single hint, right?

**Comment by sarvaje** [comment] 2018-12-17 18:08
> But we should print only one general error instead of in every single hint, right?

That is right, I forgot about that.

**Comment by sarvaje** [comment] 2018-12-17 23:49
I have found the problem. To show the error message, all the issues should fail and have the same error message, but the hints "off" we were marking them as pass, so there is the problem.

I have create a PR in the online scanner to fix this https://github.com/webhintio/online-service/pull/193

The only thing is that, this is only going to work for new scans, If we want this works for old scans, I need to do an script to change the database.

**Comment by molant** [comment] 2018-12-18 00:52
I'm fine with just new scans getting the right behavior unless you can write that script in 15min...


________________________________

**Comment by molant** [comment] 2018-12-18 04:50
@sarvaje I've merged your PR in the online scanner.
@iondrimba I've updated the title of this issue to better reflect what's going on.

Thank you both!

**Comment by iondrimba** [comment] 2018-12-18 10:09
Thank you @molant and @sarvaje for the quick response and fix 👍 💯

**Comment by sarvaje** [comment] 2018-12-19 01:01
@molant @iondrimba the fix is deployed. The fetch is still not supported, but now the result will show an error message, instead of all the hints with the same error message.

**Comment by iondrimba** [comment] 2018-12-19 01:18
Thanks @sarvaje

**Comment by molant** [comment] 2019-09-27 18:22
We've moved to `puppeteer` as the default everywhere so this shouldn't has as big of an impact as before so closing it.

**Closed by molant** 2019-09-27 18:22 UTC
Labels: area:connector, connector:jsdom, type:bug
